image: python:latest

stages:
  - ver
  - tests

ver:
  stage: ver
  script:
    - python --version
    - whoami

unit-tests:
  stage: tests
  script:
    - pip install -r requirements.txt
    - python -m unittest discover -s pokedex/app/pokedex-test.py -p '*_test.py'
