image: python:alpine-3.9

stages:
  - ver
  - tests

ver:
  stage: ver
  script:
    - python --version
    - whoami

unit-tests:
  stage: unit-tests
  script:
    - pip install -r pokedex/requirements.txt
    - python -m unittest discover -s pokedex/app/pokedex-test.py -p '*_test.py'
